---
name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "readme.md"


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - name: Clone quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          branch: 'v4'
          owner: 'jackyzha0'
          repository: 'quartz'

      - name: build
        run: >
          cd $HOME
          && git clone https://github.com/jackyzha0/quartz
          && cp $GITHUB_WORKSPACE/quartz.config.ts quartz
          && cp $GITHUB_WORKSPACE/quartz.layout.ts quartz
          && cd quartz
          && npm install
          && npx quartz create -s $GITHUB_WORKSPACE -X copy -l shortest
          && rm -rf content/quartz
          && npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /home/runner/quartz/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
